# Generated by Django 5.0.3 on 2024-04-01 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='files')),
                ('icon', models.ImageField(upload_to='files')),
                ('description', models.CharField(max_length=500)),
                ('syllabus', models.FileField(upload_to='files')),
            ],
        ),
    ]
