# Generated by Django 5.0.3 on 2024-04-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='placement')),
                ('qualification', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=20)),
                ('placed_at', models.CharField(max_length=20)),
            ],
        ),
    ]
