# Generated by Django 5.0.3 on 2024-04-02 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergio', '0002_placement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='team')),
                ('position', models.CharField(max_length=20)),
            ],
        ),
    ]
