# Generated by Django 5.0.3 on 2024-04-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergio', '0005_stories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='icon',
            field=models.ImageField(upload_to='course'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='image',
            field=models.ImageField(upload_to='course'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='syllabus',
            field=models.FileField(upload_to='course'),
        ),
    ]
