# Generated by Django 5.0.3 on 2024-04-03 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emergio', '0006_alter_courses_icon_alter_courses_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placement',
            name='name',
        ),
        migrations.RemoveField(
            model_name='placement',
            name='placed_at',
        ),
        migrations.RemoveField(
            model_name='placement',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='placement',
            name='role',
        ),
    ]
