# Generated by Django 5.0.3 on 2024-04-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergio', '0007_remove_placement_name_remove_placement_placed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=20)),
                ('experiance', models.IntegerField()),
            ],
        ),
    ]
