# Generated by Django 5.0.3 on 2024-04-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergio', '0009_alter_career_experiance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=20)),
                ('resume', models.FileField(upload_to='resumes')),
            ],
        ),
    ]
