# Generated by Django 5.0.4 on 2024-04-04 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergio', '0010_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='games')),
                ('link', models.URLField()),
                ('category', models.CharField(max_length=30)),
            ],
        ),
    ]
