# Generated by Django 5.0.4 on 2024-04-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergio', '0012_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stories',
            old_name='image',
            new_name='thumbnail',
        ),
        migrations.AddField(
            model_name='stories',
            name='link',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
