# Generated by Django 5.0.4 on 2024-04-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emergio", "0013_rename_image_stories_thumbnail_stories_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="header",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="team",
            name="position",
            field=models.CharField(max_length=50),
        ),
    ]
