# Generated by Django 5.0.4 on 2024-04-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emergio", "0014_alter_news_header_alter_team_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=50)),
                ("place", models.CharField(max_length=50)),
            ],
        ),
    ]
