# Generated by Django 5.0.4 on 2024-04-16 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emergio", "0015_gameform"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courses",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
