# Generated by Django 5.0.4 on 2024-05-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emergio", "0016_alter_courses_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="hire")),
            ],
        ),
    ]
