# Generated by Django 5.0.4 on 2024-05-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emergio", "0017_hire"),
    ]

    operations = [
        migrations.AddField(
            model_name="hire",
            name="position",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
