# Generated by Django 5.0.4 on 2024-06-07 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emergio", "0018_hire_position"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="GameForm",
            new_name="Form",
        ),
    ]
