# Generated by Django 3.2.25 on 2025-03-07 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergio', '0019_rename_gameform_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
