# Generated by Django 3.2.25 on 2025-03-07 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergio', '0020_alter_news_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(),
        ),
    ]
