# Generated by Django 3.2.25 on 2025-04-15 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emergio', '0022_auto_20250411_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leads',
            name='created_at',
        ),
    ]
