# Generated by Django 4.2.10 on 2025-05-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergio', '0023_remove_leads_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('pincode', models.CharField(max_length=20)),
                ('qualification', models.CharField(max_length=20)),
                ('dob', models.CharField(max_length=20)),
                ('domain', models.CharField(max_length=20)),
                ('secondary_phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('paymentmethod', models.CharField(max_length=20)),
            ],
        ),
    ]
