# Generated by Django 4.2.10 on 2025-05-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergio', '0024_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='career',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='career',
            name='locations',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='career',
            name='posted_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='career',
            name='experiance',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='career',
            name='position',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
