# Generated by Django 4.2.10 on 2025-05-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergio', '0025_career_category_career_description_career_locations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='locations',
            field=models.JSONField(blank=True, default=['Kochi', 'Chennai'], null=True),
        ),
    ]
