# Generated by Django 4.2.10 on 2025-05-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergio', '0027_category_alter_career_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='duration',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='first_4_topics',
            field=models.JSONField(blank=True, default={'1': 'Topic 1', '2': 'Topic 2', '3': 'Topic 3', '4': 'Topic 4'}, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='hub',
            field=models.CharField(blank=True, default='Kochi/Chennai', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='payment_method',
            field=models.CharField(blank=True, default='Online', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='price',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='sec_image',
            field=models.ImageField(blank=True, null=True, upload_to='course'),
        ),
        migrations.AddField(
            model_name='courses',
            name='short_desc',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='course'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='course'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='syllabus',
            field=models.FileField(blank=True, null=True, upload_to='course'),
        ),
    ]
