# Generated by Django 4.2.10 on 2025-05-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergio', '0028_courses_duration_courses_first_4_topics_courses_hub_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='nextbatch',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
