# Generated by Django 4.2.10 on 2025-05-16 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergio', '0029_courses_nextbatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='team_members',
            field=models.ManyToManyField(blank=True, to='emergio.team'),
        ),
    ]
