# Generated by Django 4.2.10 on 2025-05-16 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emergio', '0030_courses_team_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='team_members',
        ),
        migrations.AddField(
            model_name='team',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='emergio.courses'),
        ),
    ]
