# Generated by Django 4.2.10 on 2025-05-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergio', '0031_remove_courses_team_members_team_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='position',
            field=models.CharField(max_length=100),
        ),
    ]
