# Generated by Django 4.2.10 on 2025-05-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergio', '0032_alter_team_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='testimonial')),
                ('description', models.TextField()),
                ('url', models.URLField()),
            ],
        ),
    ]
