# Generated by Django 4.2.10 on 2025-05-22 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emergio', '0033_testimonial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='phone',
        ),
    ]
