# Generated by Django 4.2.10 on 2025-05-22 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emergio', '0034_application_career'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='career',
        ),
        migrations.RemoveField(
            model_name='application',
            name='phone',
        ),
    ]
