# Generated by Django 4.2.10 on 2025-08-11 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergio', '0034_remove_application_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='type',
            field=models.CharField(choices=[('current', 'Current Employee'), ('ex-employee', 'Ex-Employee'), ('Terminated', 'Terminated/Unhired Employee')], default='current', max_length=20),
        ),
    ]
